//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaHutNew.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartItem
    {
        public int id { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> pizzaId { get; set; }
        public int quantity { get; set; }
    
        public virtual order order { get; set; }
        public virtual pizza pizza { get; set; }
    }
}
