//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaHutNew.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class pizza
    {
        public pizza()
        {
            this.cartItems = new HashSet<cartItem>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string ingridients { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<cartItem> cartItems { get; set; }
    }
}
